replicaCount: 2
image:
  repository: myusername/my-spring-app
  tag: latest

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70

service:
  type: LoadBalancer
  port: 80

persistentVolume:
  enabled: true
  size: 5Gi
